name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.42'

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release --no-restore
    - name: Build docker image
      run: docker build -t phuongladocker/api-crypto-docker

